// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClA-RrAA1p1uHO5P6aP_ecFE_PFN2qBUk',
    appId: '1:385427513404:web:8839924b2527aee784e339',
    messagingSenderId: '385427513404',
    projectId: 'jewelryapp-69ec8',
    authDomain: 'jewelryapp-69ec8.firebaseapp.com',
    databaseURL: 'https://jewelryapp-69ec8-default-rtdb.firebaseio.com',
    storageBucket: 'jewelryapp-69ec8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnNmRMI5b51NzepfTk5H7ZiTNOm9eR7NE',
    appId: '1:385427513404:android:d4199c87383ce1d884e339',
    messagingSenderId: '385427513404',
    projectId: 'jewelryapp-69ec8',
    databaseURL: 'https://jewelryapp-69ec8-default-rtdb.firebaseio.com',
    storageBucket: 'jewelryapp-69ec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdHwcoG0kbvx27KVlU_9YRSB5GpDj9NFs',
    appId: '1:385427513404:ios:c3370f4ed33b037584e339',
    messagingSenderId: '385427513404',
    projectId: 'jewelryapp-69ec8',
    databaseURL: 'https://jewelryapp-69ec8-default-rtdb.firebaseio.com',
    storageBucket: 'jewelryapp-69ec8.firebasestorage.app',
    iosBundleId: 'com.example.enjoiJewelryApp',
  );
}
